"""empty message

Revision ID: dbf243f523c1
Revises: 
Create Date: 2025-09-18 15:38:44.975312

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dbf243f523c1'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('access_scope', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(length=22), server_default=sa.text('SUBSTR(UPPER(md5(random()::text)), 2, 22)'), nullable=False),
    sa.Column('expiration_time', sa.TIMESTAMP(), server_default=sa.text("current_timestamp + interval '2 hours'"), nullable=False),
    sa.Column('token_type', sa.String(length=22), server_default='Bearer', nullable=False),
    sa.PrimaryKeyConstraint('client_id')
    )
    op.create_table('users',
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('client_secret', sa.String(length=100), nullable=False),
    sa.Column('scope', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('client_id'),
    sa.UniqueConstraint('client_id')
    )
    op.drop_table('user')
    op.drop_table('token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token',
    sa.Column('client_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('access_scope', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('access_token', sa.VARCHAR(), server_default=sa.text('substr(upper(md5((random())::text)), 2, 22)'), autoincrement=False, nullable=True),
    sa.Column('expiration_time', postgresql.TIMESTAMP(), server_default=sa.text("(CURRENT_TIMESTAMP + '02:00:00'::interval)"), autoincrement=False, nullable=True)
    )
    op.create_table('user',
    sa.Column('client_id', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('client_secret', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('scope', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.UniqueConstraint('client_id', name=op.f('user_client_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.drop_table('users')
    op.drop_table('tokens')
    # ### end Alembic commands ###
